#!/bin/sh
# Script start or stop the aesdsocket daemon

case "$1" in 
    start)
        echo "Starting aesdsocket daemon"
        start-stop-daemon --background -S -n aesdsocket -a /usr/bin/aesdsocket
    ;;
    stop)
        echo "Stopping aesdsocket daemon"
        start-stop-daemon -K -n aesdsocket
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
    ;;
esac
exit 0